version: '3.8'

services:
  web:
    image: node:20.11.1
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app

  mongoboo:
    env_file: ./.env
    build:
      context: ./.devcontainer/mongo
      dockerfile: Dockerfile
    restart: always
    container_name: mongoboo
    hostname: mongoboo
    command:
      [
        '--replSet',
        'rs0',
        '--bind_ip_all',
        '--port',
        '27017',
        '--keyFile',
        '/etc/mongodb/pki/keyfile',
      ]
    volumes:
      - './.devcontainer/mongo/mongo1_data:/data/db'
      - './.devcontainer/mongo/mongo1_config:/data/configdb'
      - './.devcontainer/mongo/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongoboo:27017'}]}) }" | mongosh --port 27017 --quiet -u root -p root
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

  mongoboo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: ./.env
