apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.host | replace "." "-" }}-cert
spec:
  secretName: {{ .Values.ingress.host | replace "." "-" }}-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}